server:
  port: 8888

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/devshop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false
  main:
    allow-bean-definition-overriding: true


mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.dev.shop.**.dto
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null



logging:
  level:
    org.springframework.security: DEBUG
    jdbc:
      resultsettable: info
      audit: off
      connection: off
      resultset: off



